name: Deploy React App
permissions:
  contents: write
on:
  workflow_dispatch:
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build 
          branch: secondary/Tailwind
        